#!/usr/bin/env python3

import argparse
import numpy as np

def make_matrices(m, n, p):
    A = np.random.rand(m, n)
    B = np.random.rand(n, p)
    C = A.dot(B)
    np.savetxt('matrix_a', A.flatten(), fmt='%.8f')
    np.savetxt('matrix_b', B.flatten(), fmt='%.8f')
    np.savetxt('matrix_c', C.flatten(), fmt='%.8f')

parser = argparse.ArgumentParser(description='Generates A (m x n), B (n x p), and C = A*B (m x p) matrices with given dimensions (m, n, p)')
parser.add_argument('m', metavar='m', type=int, help='number of rows in matrix A')
parser.add_argument('n', metavar='n', type=int, help='number of columns in matrix A / rows in matrix B')
parser.add_argument('p', metavar='p', type=int, help='number of columns in matrix B')

args = parser.parse_args()
make_matrices(args.m, args.n, args.p)
